name: Envoi automatique du menu CROUS

on:
  schedule:
    # 09h00 UTC = 11h00 France
    - cron: '0 9 * * 1-6'
  workflow_dispatch:  # Manuelle

jobs:
  send-menu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code 🛎️
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer les dépendances
        run: npm ci

      - name: Envoyer le menu sur Discord
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          RESTO_URL: https://www.crous-bordeaux.fr/restaurant/resto-u-n2-3/
        run: node ./src/autoSend.js
