name: Envoi du menu Discord

on:
  schedule:
    - cron: '0 9 * * 1-6' # 11h00 heure de France (9h UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code 🛎️
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer les dépendances
        run: npm ci

      - name: Vérifier la variable BOT_TOKEN
        run: |
          if [ -z "$BOT_TOKEN" ]; then
            echo "❌ BOT_TOKEN est vide !"
            exit 1
          else
            echo "✅ BOT_TOKEN chargé."
          fi
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Exécuter le bot Discord
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: node ./src/autoSend.js
